benchmarks:
  ExternalTestBench:
    waittimes:
    - 1
    - 4
    - 8

collection_modes:
  memory: null
  perf:
    pmu_count: 4

formatter_modes:
- PandasPickle
- CSV

perf_counters:
- instructions
- cpu-cycles
- LLC-stores
- page-faults
- major-faults

iterations: 1
log: true
test_name: test
time_count: 1000

