benchmarks:
  - type: generic_benchmark 
    name: NamedTest
    cmd: echo "Hi I'm echoing; sleep 1"
  
  - type: TestBench
    name: NameOfThisTestBench
    waittimes:
      - 1
      - 4
      - 3

collection_modes:
  ttc:
    - ''
  utilization:
    - memory_info

formatter_modes:
- PandasPickle
- CSV

iterations: 1
log: true
time_count: 1000
test_name: test_application
