benchmarks:
  - type: TestBench
    name: aaaaaTestBench
    waittimes:
      - 1
      - 4
  - type: generic_benchmark 
    cmd: echo "Hi I'm echoing; sleep 1"
    name: NamedTest

collection_modes:
  ttc:
    - ''
  utilization:
    - memory_info

formatter_modes:
- PandasPickle
- CSV

iterations: 1
log: true
test_name: test_application
time_count: 1000
